
package ru.naumen.thomsonreuters.client.auth;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WOKMWSAuthenticate", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WOKMWSAuthenticate {


    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws InvalidInputException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "ru.naumen.thomsonreuters.client.auth.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "ru.naumen.thomsonreuters.client.auth.AuthenticateResponse")
    public String authenticate()
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @throws InvalidInputException_Exception
     * @throws AuthenticationException_Exception
     * @throws ESTIWSException_Exception
     * @throws SessionException_Exception
     * @throws QueryException_Exception
     * @throws InternalServerException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "ru.naumen.thomsonreuters.client.auth.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://auth.cxf.wokmws.thomsonreuters.com", className = "ru.naumen.thomsonreuters.client.auth.CloseSessionResponse")
    public void closeSession()
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

}
