
package ru.naumen.thomsonreuters.client.search;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QueryException", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com")
public class QueryException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QueryException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QueryException_Exception(String message, QueryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QueryException_Exception(String message, QueryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.naumen.thomsonreuters.client.search.QueryException
     */
    public QueryException getFaultInfo() {
        return faultInfo;
    }

}
